# Generated by Django 4.2 on 2025-06-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelisflix', '0002_movie_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='image_filename',
            field=models.CharField(blank=True, help_text='Nombre del archivo de imagen en static/pelisflix/img/', max_length=100),
        ),
    ]
